param(
    [string]$SourceDir = "",
    [string]$OutputDir = ""
)

$ErrorActionPreference = "Stop"

$SoftwareDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepositoryRoot = Split-Path -Parent $SoftwareDir
$BrushVersion = "v0.3.0"
$BrushCommit = "3edecbb2fe79d3e2c87eeab85b15e0b1dd10d486"
$PatchFile = Join-Path $SoftwareDir "patches\brush-v0.3.0-full-viewport.patch"
$CargoTargetDir = Join-Path $RepositoryRoot ".build\brush-target-v0.3.0"

$SmartAppControl = Get-ItemProperty `
    -LiteralPath "HKLM:\SYSTEM\CurrentControlSet\Control\CI\Policy" `
    -ErrorAction SilentlyContinue
if ($SmartAppControl.VerifiedAndReputablePolicyState -eq 1) {
    throw @"
Smart App Control is enabled and blocks the unsigned executables and DLLs
generated by Rust during compilation. Windows does not support per-application
exceptions for this policy. Build Brush on another machine or CI runner, or
disable Smart App Control manually before running this script.
"@
}

if (-not $SourceDir) {
    $SourceDir = Join-Path $RepositoryRoot ".build\brush-v0.3.0"
}
if (-not $OutputDir) {
    $OutputDir = Join-Path $RepositoryRoot "Brush"
}

$Git = Get-Command git -ErrorAction Stop
$LocalCargoHome = Join-Path $RepositoryRoot ".rust\cargo"
$LocalRustupHome = Join-Path $RepositoryRoot ".rust\rustup"
$LocalCargo = Join-Path $LocalCargoHome "bin\cargo.exe"
if (Test-Path -LiteralPath $LocalCargo -PathType Leaf) {
    $env:CARGO_HOME = $LocalCargoHome
    $env:RUSTUP_HOME = $LocalRustupHome
    $CargoExecutable = $LocalCargo
} else {
    $CargoExecutable = (Get-Command cargo -ErrorAction Stop).Source
}

if (-not (Test-Path -LiteralPath $SourceDir -PathType Container)) {
    New-Item -ItemType Directory -Path (Split-Path -Parent $SourceDir) -Force | Out-Null
    & $Git.Source clone --depth 1 --branch $BrushVersion `
        https://github.com/ArthurBrussee/brush.git $SourceDir
    if ($LASTEXITCODE -ne 0) {
        throw "Failed to download Brush $BrushVersion."
    }
}

$CurrentCommit = (& $Git.Source -C $SourceDir rev-parse HEAD).Trim()
if ($CurrentCommit -ne $BrushCommit) {
    throw "Brush source is at '$CurrentCommit'; expected '$BrushCommit'."
}

$PreviousErrorActionPreference = $ErrorActionPreference
$ErrorActionPreference = "Continue"
& $Git.Source -C $SourceDir apply --check $PatchFile 2>$null
$PatchCanBeApplied = $LASTEXITCODE -eq 0
$ErrorActionPreference = $PreviousErrorActionPreference

if ($PatchCanBeApplied) {
    & $Git.Source -C $SourceDir apply $PatchFile
    if ($LASTEXITCODE -ne 0) {
        throw "Failed to apply the Brush viewport patch."
    }
} else {
    $ErrorActionPreference = "Continue"
    & $Git.Source -C $SourceDir apply --reverse --check $PatchFile 2>$null
    $PatchIsAlreadyApplied = $LASTEXITCODE -eq 0
    $ErrorActionPreference = $PreviousErrorActionPreference
    if (-not $PatchIsAlreadyApplied) {
        throw "Brush source is neither clean nor already patched."
    }
}

$env:CARGO_TARGET_DIR = $CargoTargetDir
& $CargoExecutable build --manifest-path (Join-Path $SourceDir "Cargo.toml") `
    --release --package brush-app --bin brush_app
if ($LASTEXITCODE -ne 0) {
    throw "Brush compilation failed."
}

$BuiltExecutable = Join-Path $CargoTargetDir "release\brush_app.exe"
if (-not (Test-Path -LiteralPath $BuiltExecutable -PathType Leaf)) {
    throw "The compiled brush_app.exe was not found."
}

New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
Copy-Item -LiteralPath $BuiltExecutable `
    -Destination (Join-Path $OutputDir "brush_app.exe") -Force

Write-Host "Patched Brush executable: $(Join-Path $OutputDir 'brush_app.exe')"
